#odoo-staging.yml
version: '2'

services:
  db:
    image: postgres:17
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=2o0d2o4o18@2024
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks: [default]   # stays private

  odoo18:
    image: odoo:18
    user: root
    depends_on:
      - db
      - mailhog
    ports:
      - "10055:8069"   # main Odoo
      - "20055:8072"   # live chat
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=2o0d2o4o18@2024
    volumes:
      # - /etc/timezone:/etc/timezone:ro
      # - /etc/localtime:/etc/localtime:ro
      #- ./entrypoint.sh:/entrypoint.sh
      - ./opt/shared/enterprise/18.0/odoo/addons:/mnt/enterprise
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always
    networks:
      - default      # auto private net
      - edge         # shared proxy net (external)
    # no ports if using a reverse proxy

mailhog:
    image: mailhog/mailhog:v1.0.1
    restart: unless-stopped
    # Web UI on 8025, SMTP on 1025
    ports:
      - "1025:1025"   # SMTP catch-all
      - "8025:8025"   # MailHog UI
    networks:
      - default
      # If you want to expose the UI via your reverse proxy instead of a host port:
      # - edge
    # For Traefik users, you can proxy MailHog UI with labels (optional):
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.docker.network=edge"
    #   - "traefik.http.routers.mailhog.rule=Host(`mailhog.yourdomain.com`)"
    #   - "traefik.http.routers.mailhog.entrypoints=websecure"
    #   - "traefik.http.routers.mailhog.tls=true"
    #   - "traefik.http.services.mailhog.loadbalancer.server.port=8025"



networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1


#networks:
  #edge:
   # external: true        # docker network create edge

