---  # odoo-staging.yml
version: "3.8"

services:
  db:
    image: postgres:17
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=2o0d2o4o18@2024
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - default

  #mailhog:
   # image: mailhog/mailhog:latest
    #restart: unless-stopped
    # Only expose the UI locally; don't publish SMTP to host (avoids 1025 conflict)
    #ports:
     # - "0.0.0.0:8025:8025"
    #networks:
     # - default

  odoo18:
    image: odoo:18
    user: root
    depends_on:
      - db
      #- mailhog
    ports:
      - "10055:8069"   # Odoo web
      - "20055:8072"   # live chat
    tty: true
    # NOTE: do NOT set "command: --" (breaks entrypoint)
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=2o0d2o4o18@2024
      # The official image ignores ODOO_SMTP_* envs; set SMTP in /etc/odoo/odoo.conf or UI
    volumes:
      - ./opt/shared/enterprise/18.0/odoo/addons:/mnt/enterprise
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always
    networks:
      - default

networks:
  default:
    driver: bridge
